site_name: SpinoDB
nav:
    - Home: index.md
    - 'Getting Started': getting_started.md
    - 'Query Language': query_language.md
    - 'Cursor Scripts': cursor_scripts.md
    - 'API Reference': 
        - Database: api/database.md
        - Collection: api/collection.md
        - Cursor: api/cursor.md
theme: readthedocs
